### PR TITLE
Suppress parameter

### LINKED ISSUE #372: --suppress
Would be great to have an ability to suppress certain patterns:

```
$ aibolit recommend --suppress=P10,P21 test.java
```

These patterns will be ignored.

### PR DESCRIPTION
**Pull request by lyriccoder**
fix #372

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#380](https://github.com/yegor256/aibolit/issues/380) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/489f5781-dfa2-4b26-86be-5de2146101bb); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by acheshkov** [comment]
@rultor merge

**Comment by lyriccoder** [comment]
@acheshkov, need to merge again. By some reason there was a bad merge while github said everything was ok

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 21 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)[/z](https://www.0crat.com/u/paulodamaso) didn't make CR comments

**Pull request merged**
