### PR TITLE
Fix empty rethrow when we have chaining exceptions

### PR DESCRIPTION
**Pull request by lyriccoder**
Fixing https://github.com/yegor256/aibolit/issues/180

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#181](https://github.com/yegor256/aibolit/issues/181) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/1fd90828-93c0-4f1e-874a-1341f07ae7e8); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by acheshkov** [comment]
@0crat reject

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat reject ([here](https://github.com/yegor256/aibolit/issues/181#issuecomment-611039457))

@acheshkov The user @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) resigned from [#181](https://github.com/yegor256/aibolit/issues/181), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
This pull request [#181](https://github.com/yegor256/aibolit/issues/181) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/c3c2e568-6ccf-4c43-9703-c9f6ceb05112); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 18 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)[/z](https://www.0crat.com/u/carlosmiranda) didn't make CR comments

**Pull request merged**
