### PR TITLE
Fix super, it fails when arguments in javalang was not a list

### PR DESCRIPTION
**Pull request by lyriccoder**
https://github.com/yegor256/aibolit/issues/71

### CODE REVIEW

**Comment by paulodamaso** [comment]
@yegor256 I'm available for review, please assign me

**Comment by acheshkov** [comment]
@lyriccoder please add test case for this fix

**Comment by 0crat** [comment]
@lyriccoder[/z](https://www.0crat.com/u/lyriccoder) this pull request is too small, just 5 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#72` is not assigned, can't get performer

**Pull request merged**
