### PR TITLE
variable declaration in the middle of the method

### PR DESCRIPTION
**Pull request by acheshkov**

### CODE REVIEW

**Comment by g4s8** [comment]
@0crat elect

**Comment by yegor256** [comment]
@acheshkov thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#17` is not assigned, can't get performer

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Pull request merged**
