### PR TITLE
Class methods and fields usage graph

### PR DESCRIPTION
**Pull request by aravij**
API changed to be more convenient. Now accessing package classes you get dict with class name mapped to class itself. Same thing with JavaClass.
used_method property for JavaClassMethod is added.
All cached properties, which return Iterator now return Lists or Dicts.
Caching is now done with cache_property backport library. It allows using 3.8 python functionality in current 3.7 version.

### CODE REVIEW

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @aravij[/z](https://www.0crat.com/u/aravij) are: `DEV`, `REV`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@54bbf007-af81-47f4-889b-85871a7a9b4d, thread: PQ-CT5UB7XAP
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Evaluate pattern on arbitary AST' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [462bcbbf-acad-426b-b378-0bae0828f741](https://www.0crat.com/footprint/CT5UB7XAP/462bcbbf-acad-426b-b378-0bae0828f741), Type: "Job milestoned"

**Comment by 0crat** [comment]
This pull request [#420](https://github.com/yegor256/aibolit/issues/420) is assigned to @aravij[/z](https://www.0crat.com/u/aravij), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/9fe6c8eb-16d0-4dfa-8d87-21811ba554ac); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 26 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @aravij[/z](https://www.0crat.com/u/aravij)[/z](https://www.0crat.com/u/aravij) didn't make CR comments

**Pull request merged**
