### PR TITLE
Couldn't resist

### PR DESCRIPTION
**Pull request by WillDrug**
*not tested!!*
Pattern module nested_blocks.py:
1) bugfixes
2) typing fixes
3) annotation fixes
4) minified LOC

Suggestions:
change
```def value()```
to
```
@property
def value()
```

Usage then changes from `instance.value()` to `instance.value`

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#44](https://github.com/yegor256/aibolit/issues/44) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/2b1f65e9-2370-487f-ad4b-1a67a7ba1824); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@WillDrug what ticket (Github issue) is this PR supposed to be fixing?

**Comment by WillDrug** [comment]
@carlosmiranda none. this is a bugfix and a bit of styling.

**Comment by carlosmiranda** [comment]
@WillDrug please close this PR, first raise tickets for each specific bug that you find and then send the corresponding pull requests. We do not accept generic catch-all pull requests, makes it difficult to track.

**Comment by 0crat** [comment]
Job audit: `ARC` didn't merge or close PR

**Comment by 0crat** [comment]
Job was finished in 36 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Pull request [#44](https://github.com/yegor256/aibolit/issues/44) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by 0crat** [comment]
Order was finished: +20 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Pull request closed without merging**
