### PR TITLE
For #194: added tests to this_finder

### PR DESCRIPTION
**Pull request by paulodamaso**
For #194:
Added the clases to this_finder tests:
- `BookMarkEditCmd. java` does not have any pattern to be found by `this_find`
- `ChainedBuffer. java` throws an exception
- `CliMethodExtraSections. java` does not have any pattern to be found by `this_find`
- `LoaderInfoHeader. java` throws an exception
- `OmfModuleEnd. java` does not have any pattern to be found by `this_find`

### CODE REVIEW

**Comment by paulodamaso** [comment]
@lyriccoder Fixed the bug, exception is not triggered in `ChainedBuffer.java` and `LoaderInfoHeader.java` anymore

**Comment by acheshkov** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@acheshkov Sorry for the error, fixed now, please take a look.

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#241` is not assigned, can't get performer

**Pull request merged**
