### PR TITLE
Introducing type-checking to whole project

### PR DESCRIPTION
**Pull request by tribals**
For #130.

Some considerations:

Right now, performing checking yields several errors:

```console
$ make typecheck
mypy aibolit
aibolit/patterns/non_final_attribute/non_final_attribute.py:30: error: List comprehension has incompatible type List[FieldDeclaration]; expected List[int]
aibolit/metrics/entropy/entropy.py:25: error: Skipping analyzing 'numpy': found module but no type hints or library stubs
aibolit/metrics/entropy/entropy.py:25: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
aibolit/metrics/entropy/entropy.py:26: error: Skipping analyzing 'scipy.stats': found module but no type hints or library stubs
aibolit/patterns/return_null/return_null.py:47: error: "Expression" has no attribute "value"
aibolit/patterns/nested_blocks/nested_blocks.py:97: error: Missing return statement
aibolit/patterns/nested_blocks/nested_blocks.py:99: error: "Node" has no attribute "_position"; maybe "position"?
aibolit/patterns/multiple_try/multiple_try.py:63: error: Item "InferredFormalParameter" of "Union[FormalParameter, InferredFormalParameter]" has no attribute "type"
aibolit/patterns/implements_multi/implements_multi.py:12: error: "ClassDeclaration" has no attribute "_position"
aibolit/patterns/er_class/er_class.py:26: error: "ClassDeclaration" has no attribute "_position"
aibolit/__main__.py:47: error: Skipping analyzing 'aibolit.model.model': found module but no type hints or library stubs
Found 10 errors in 8 files (checked 67 source files)
make: *** [Makefile:33: typecheck] Error 1
```

I hadn't fixed them intentionally. These errors introduced by task performers, not me. The only goal of this PR is to enable static type checking itself and not to fix already existing errors.

I also didn't enabled checking for `aibolit/metrics` and `aibolit/model`. The reason is that they use very sophisticated libraries as dependencies - they all related to machine learning/neural networks. I don't have enough expertise in these libraries for proper annotating our own code. But this is not a stop factor for enabling type checking for the rest of project. Please, see: https://mypy.readthedocs.io/en/stable/existing_code.html

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#165](https://github.com/yegor256/aibolit/issues/165) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/ab60d51f-fbcf-4ce5-8a0a-7096a4b883d3); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by fanifieiev** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/aibolit/issues/165#issuecomment-609547954))

@fanifieiev The user @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) resigned from [#165](https://github.com/yegor256/aibolit/issues/165), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/aibolit/issues/165#issuecomment-609547954))

@fanifieiev Job refused in 2 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
This pull request [#165](https://github.com/yegor256/aibolit/issues/165) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/f7277848-bf73-4414-a8c4-4736bc498702); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/aibolit/issues/165#issuecomment-609583972))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#165](https://github.com/yegor256/aibolit/issues/165), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/aibolit/issues/165#issuecomment-609583972))

@carlosmiranda Job refused in 1 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
This pull request [#165](https://github.com/yegor256/aibolit/issues/165) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/ad6fd4c1-738e-4430-8b4a-00c6dfb56c0d); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by acheshkov** [comment]
@rultor merge

**Comment by tribals** [comment]
@acheshkov Let's try again.

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@0crat pay @tribals 120

**Comment by 0crat** [comment]
> @0crat pay @tribals 120 ([here](https://github.com/yegor256/aibolit/issues/165#issuecomment-609924158))

@acheshkov Argument "@tribals" doesn't match regex `\d+min`

**Comment by 0crat** [comment]
Job was finished in 10 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)[/z](https://www.0crat.com/u/paulodamaso) didn't make CR comments

**Comment by acheshkov** [comment]
@0crat pay @tribals 120min

**Comment by 0crat** [comment]
> @0crat pay @tribals 120min ([here](https://github.com/yegor256/aibolit/issues/165#issuecomment-609935637))

@acheshkov Argument "@tribals" doesn't match regex `\d+min`

**Comment by acheshkov** [comment]
@0crat pay 120min

**Comment by 0crat** [comment]
> @0crat pay 120min ([here](https://github.com/yegor256/aibolit/issues/165#issuecomment-609941788))

@acheshkov Option `<login>` is missing in `pay <minutes> <login>`:
  \* `<login>`: GitHub name of the user
  \* `<minutes>`: how many minutes to pay

**Comment by acheshkov** [comment]
@0crat pay 120 @tribals

**Comment by 0crat** [comment]
> @0crat pay 120 @tribals  ([here](https://github.com/yegor256/aibolit/issues/165#issuecomment-609950174))

@acheshkov Argument "120" doesn't match regex `\d+min`

**Comment by acheshkov** [comment]
@0crat pay 120min @tribals

**Pull request merged**
