### PR TITLE
For #148: added send_null pattern

### PR DESCRIPTION
**Pull request by paulodamaso**
For #148:
- Added send_null pattern
- added test cases

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#211](https://github.com/yegor256/aibolit/issues/211) is assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/0f6b81a0-d35b-4496-8164-e7a46fa357c8); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by lyriccoder** [comment]
@paulodamaso this issue have been alerady implemented by @silverCase  in https://github.com/yegor256/aibolit/pull/197. We need to close it

**Comment by paulodamaso** [comment]
@lyriccoder @0crat assigned it to me (https://github.com/yegor256/aibolit/issues/148#issuecomment-613540460). Do you want me to close the PR?

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/aibolit/issues/211#issuecomment-614004311); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by lyriccoder** [comment]
@acheshkov what should we do?

**Comment by acheshkov** [comment]
I'm closing this PR, @paulodamaso please check it out that you are paid for this task. If not, please contact technical support

**Comment by 0crat** [comment]
Job was finished in 22 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Pull request [#211](https://github.com/yegor256/aibolit/issues/211) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
