### PR TITLE
null_check pattern

### LINKED ISSUE #89: null_check pattern
This is the pattern:

```
class Foo {
  private String z;
  void x() {
    if (this.z == null) { // here!
      throw new RuntimeException("oops");
    }
  }
}
```

The check for `null` is the pattern.

The pattern should not check constructors.

### PR DESCRIPTION
**Pull request by tribals**
Add `null_check` pattern. Closes #89

### CODE REVIEW

**Comment by lyriccoder** [comment]
1) @yegor256  Should we check this patterns also (they are not catched by the provided code):

`boolean i = z == null;`
`boolean i = z != null;`
`luckyName != null ? luckyName : "No lucky name found";`
`if (z != null)`
`luckyName == null ? luckyName : "No lucky name found";`
`assert param != null;`
`assertThrows(NullPointerException.class, () -> wrapperSum(null, 2));`
`Optional<String> op2 
            = Optional.ofNullable(null); `
`if (one == null || two == null || three == null)`
`Objects.requireNonNull(bar, "bar must not be null");`
`public void accept(String param){
    if (null != param && !param.isEmpty())
        System.out.println(param);
}`

2) Could you please also check the line numbers in test cases, not a length of an array. 
E.g., `Pattern.value('java.java') == [3, 105, 660]`

**Comment by tribals** [comment]
> 1. Could you please also check the line numbers in test cases, not a length of an array.
>    E.g., `Pattern.value('java.java') == [3, 105, 660]`

Good idea! Will do so.

**Comment by tribals** [comment]
Actually it will catch any binary expression where the operation is "equal" and right operand is `null', be it in `if` condition (either single or multiple combined with Boolean operators), in assignment or ternary.

It _will not_ catch "not equal" operations, though. As well when `null` is the left operand - this is weird but valid case.

**Comment by yegor256** [comment]
@lyriccoder looks good to me as is. We can later improve it.

**Comment by tribals** [comment]
@lyriccoder @acheshkov Please, do review. I will merge PR then.

**Comment by tribals** [comment]
@lyriccoder @yegor256 @acheshkov Can anyone please re-trigger Travis build in some way?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@tribals tests fail here, sorry

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#103` is not assigned, can't get performer

**Pull request merged**
