### PR TITLE
started impelement cognitive complexity

### PR DESCRIPTION
**Pull request by Vitaly-Protasov**
#206  First step for impelementing cognitive complexity.

Me and @lukyanoffpashok view only two simple instances how cognitive complexity need to be considered.

We implemented incrementing only for and if - elif statements without nesting firstly.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#207](https://github.com/yegor256/aibolit/issues/207) is assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/abc9541e-2b0f-4e32-a85c-989aed211380); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 22 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @lyriccoder[/z](https://www.0crat.com/u/lyriccoder)[/z](https://www.0crat.com/u/lyriccoder) didn't make CR comments

**Pull request merged**
