### PR TITLE
Fix case for SpaceCounter when we have 0 or 1 lines

### PR DESCRIPTION
**Pull request by lyriccoder**
fixing https://github.com/yegor256/aibolit/issues/192

### CODE REVIEW

**Comment by acheshkov** [comment]
@0crat reject

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat reject ([here](https://github.com/yegor256/aibolit/issues/193#issuecomment-611952961))

@acheshkov Job `gh:yegor256/aibolit#193` is not assigned, can't get performer

**Comment by 0crat** [comment]
This pull request [#193](https://github.com/yegor256/aibolit/issues/193) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/da0fe0a9-77e8-4a9c-b32c-af74845d390e); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)[/z](https://www.0crat.com/u/carlosmiranda) didn't make CR comments

**Pull request merged**
