### PR TITLE
fixed issue #177

### PR DESCRIPTION
**Pull request by acheshkov**
fixed issue #177

### CODE REVIEW

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @acheshkov[/z](https://www.0crat.com/u/acheshkov) please review this and merge or reject

**Comment by acheshkov** [comment]
@lyriccoder

**Comment by lyriccoder** [comment]
I will check it

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@0crat reject

**Comment by 0crat** [comment]
> @0crat reject  ([here](https://github.com/yegor256/aibolit/issues/178#issuecomment-610999191))

@acheshkov Job `gh:yegor256/aibolit#178` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#178` is not assigned, can't get performer

**Pull request merged**
