### PR TITLE
Task #9 Implement correct Lines of Code metric

### PR DESCRIPTION
**Pull request by zuoqin**

### CODE REVIEW

**Comment by yegor256** [comment]
@zuoqin there are merge conflicts, please fix them

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) not enough funds available in the project, can't set budget of job [#10](https://github.com/yegor256/aibolit/issues/10), see [§21](http://www.zerocracy.com/policy.html#21); @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by g4s8** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda ([here](https://github.com/yegor256/aibolit/issues/10#issuecomment-582284155))

@g4s8 Job [#10](https://github.com/yegor256/aibolit/issues/10) is already assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by carlosmiranda** [comment]
@g4s8 it's weird, this job isn't showing up in my agenda

**Comment by carlosmiranda** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/aibolit/issues/10#issuecomment-582744908))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#10](https://github.com/yegor256/aibolit/issues/10), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/aibolit/issues/10#issuecomment-582744977))

@carlosmiranda This is what I know about this job in [CT5UB7XAP](https://www.0crat.com/p/CT5UB7XAP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#10](https://github.com/yegor256/aibolit/issues/10) is [in scope](http://www.zerocracy.com/policy.html#14) for 2days
  * The role is `REV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @zuoqin[/z](https://www.0crat.com/u/zuoqin): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT5UB7XAP?q=%7Bjob%3A%27gh%3Ayegor256%2Faibolit%2310%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Tasks refusal is discouraged (job refused in 38 hours), see [§6](http://www.zerocracy.com/policy.html#6): -10 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
This pull request [#10](https://github.com/yegor256/aibolit/issues/10) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/2a4168a0-2d87-4886-a917-b90f9f6864c4); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by fanifieiev** [comment]
@zuoqin Which issue is this PR for???
Could you please post a link to the relevant issue in the description of this PR ????

**Comment by yegor256** [comment]
@zuoqin what's up with this?

**Comment by fanifieiev** [comment]
@zuoqin Please pay attention to the comments.

**Comment by fanifieiev** [comment]
@yegor256 This PR has been open for 8 days.
The performer is not reacting to the comments. 
IMHO the [comments ](https://github.com/yegor256/aibolit/pull/10#pullrequestreview-354626931) I listed are important.
Please suggest the next step: deny or wait???.

**Comment by yegor256** [comment]
@zuoqin not required anymore

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#10` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by fanifieiev** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/aibolit/issues/10#issuecomment-587775799))

@fanifieiev This is what I know about this job in [CT5UB7XAP](https://www.0crat.com/p/CT5UB7XAP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#10](https://github.com/yegor256/aibolit/issues/10) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT5UB7XAP?q=%7Bjob%3A%27gh%3Ayegor256%2Faibolit%2310%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by fanifieiev** [comment]
@yegor256 @g4s8 I reviewed this PR and requested that changes are done by DEV, The DEV did not show up, the PR was closed manually.
As a result I did not get any points and payment.
Is it the way it works in this project????????

**Pull request closed without merging**
