### PR TITLE
scope of work planning, April

### PR DESCRIPTION
**Pull request by acheshkov**
Scope of work how we see at the beginning of the April

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#152](https://github.com/yegor256/aibolit/issues/152) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/61c7fbcb-bb62-44b0-bfac-c4d8c6c4399d); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by yegor256** [comment]
@acheshkov looks good to me

**Comment by fanifieiev** [comment]
@acheshkov Sorry, I do not think I can honestly evaluate the scope. 
I beleive that if @yegor256 and you are fine with that, than it is worth merging.

**Comment by acheshkov** [comment]
@0crat reject

**Comment by 0crat** [comment]
> @0crat reject ([here](https://github.com/yegor256/aibolit/issues/152#issuecomment-607942258))

@acheshkov The user @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) resigned from [#152](https://github.com/yegor256/aibolit/issues/152), please stop working. Reason for job resignation: Order was cancelled

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#152` is not assigned, can't get performer

**Pull request merged**
