### PR TITLE
Fix string concat

### PR DESCRIPTION
**Pull request by lyriccoder**
Fixing https://github.com/yegor256/aibolit/issues/190

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#191](https://github.com/yegor256/aibolit/issues/191) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/09ce823f-c57a-4772-b54a-0719ba37230c); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by acheshkov** [comment]
@0crat reject

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat reject ([here](https://github.com/yegor256/aibolit/issues/191#issuecomment-611953939))

@acheshkov The user @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) resigned from [#191](https://github.com/yegor256/aibolit/issues/191), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
This pull request [#191](https://github.com/yegor256/aibolit/issues/191) is assigned to @tribals[/z](https://www.0crat.com/u/tribals), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/979c2030-30cd-430c-be9f-9e75431e149f); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job audit: performer @tribals[/z](https://www.0crat.com/u/tribals)[/z](https://www.0crat.com/u/tribals) didn't make CR comments

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Pull request merged**
