### PR TITLE
Docs update

### PR DESCRIPTION
**Pull request by lyriccoder**
fixing https://github.com/yegor256/aibolit/issues/298

### CODE REVIEW

**Comment by acheshkov** [comment]
@0crat out

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/299#issuecomment-628565191))

@acheshkov Job `gh:yegor256/aibolit#299` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/299#issuecomment-628565191))

@acheshkov Pull request [#299](https://github.com/yegor256/aibolit/issues/299) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#299` is not assigned, can't get performer

**Pull request merged**
