### PR TITLE
Demo version of model prediction

### PR DESCRIPTION
**Pull request by lyriccoder**
https://github.com/yegor256/aibolit/issues/81

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@lyriccoder you need to mark `.jar` files in `.gitattributes`

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#82` is not assigned, can't get performer

**Pull request merged**
