### PR TITLE
Fix issue 363

### PR DESCRIPTION
**Pull request by lyriccoder**
fix https://github.com/yegor256/aibolit/issues/363

### CODE REVIEW

**Comment by lyriccoder** [comment]
recommend --folder D:\temp\temp_test --full --format=compact --exclude=**/*Test*.java --exclude=D:/git/aibolit/ --exclude=D:/temp/

**Comment by lyriccoder** [comment]
@yegor256 is it ok now?

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#427` is not assigned, can't get performer

**Pull request merged**
