### PR TITLE
Fix config #401 

### LINKED ISSUE #401: prepare config for new release
Need to remove duplicates in config
Need to add new metrics implemented by @Vitaly-Protasov

### PR DESCRIPTION
**Pull request by lyriccoder**
Fix #401

### CODE REVIEW

**Comment by 0crat** [comment]
@lyriccoder[/z](https://www.0crat.com/u/lyriccoder) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @acheshkov[/z](https://www.0crat.com/u/acheshkov) please review this and merge or reject

**Comment by lyriccoder** [comment]
@0crat wait

I need to calculate patterns and check if everything is ok, seems we will merge it only tonight

**Comment by 0crat** [comment]
> @0crat wait I need to calculate patterns and check if everything is ok, seems we will merge it... ([here](https://github.com/yegor256/aibolit/issues/402#issuecomment-641943358))

@lyriccoder Job `gh:yegor256/aibolit#402` is not assigned, can't get performer

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#402` is not assigned, can't get performer

**Pull request merged**
