### PR TITLE
Issue 340. Refactoring.

### PR DESCRIPTION
**Pull request by aravij**
Functionality of AST was splited into two separate modules: encoding_detector and ast_builder.
This refactoring also decrease number of times we read file, while building ast (from 2 to 1).

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#387](https://github.com/yegor256/aibolit/issues/387) is assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/587aa854-af34-4447-a932-5d77df2db09a); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by aravij** [comment]
PR is going to be declined in order to be moved in a separate branch.

**Comment by 0crat** [comment]
Job was finished in 4 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: `ARC` didn't merge or close PR, performer @lyriccoder[/z](https://www.0crat.com/u/lyriccoder)[/z](https://www.0crat.com/u/lyriccoder) didn't make CR comments

**Comment by 0crat** [comment]
Pull request [#387](https://github.com/yegor256/aibolit/issues/387) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
