### PR TITLE
Fix for Redundant catch

### PR DESCRIPTION
**Pull request by lyriccoder**
https://github.com/yegor256/aibolit/issues/172

### CODE REVIEW

**Comment by acheshkov** [comment]
@0crat reject

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat reject  ([here](https://github.com/yegor256/aibolit/issues/173#issuecomment-610876559))

@acheshkov Job `gh:yegor256/aibolit#173` is not assigned, can't get performer

**Comment by 0crat** [comment]
This pull request [#173](https://github.com/yegor256/aibolit/issues/173) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/2bc92647-62c0-4abc-8240-e53097867fdc); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job audit: performer @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)[/z](https://www.0crat.com/u/fanifieiev) didn't make CR comments

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 15@731e041f0a87, thread: PQ-CT5UB7XAP
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-boosts.xsl says: The boost for job "gh:yegor256/aibolit#173" exists in boosts.xml, but the job is absent in the WBS among 22 jobs.
```

[0.52.15](https://github.com/zerocracy/farm): CID: [c8281888-6fab-4b3b-975c-7dbb51f8f59e](https://www.0crat.com/footprint/CT5UB7XAP/c8281888-6fab-4b3b-975c-7dbb51f8f59e), Type: "Remove job from WBS"

**Pull request merged**
