### PR TITLE
For #184: added local method called metric tests

### PR DESCRIPTION
**Pull request by paulodamaso**
For #184:
- added local method called metric tests
- left puzzle to continue implementation of local method called metric

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#244](https://github.com/yegor256/aibolit/issues/244) is assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/e01118e3-5c5c-41de-9891-1c4672e1f95e); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by lyriccoder** [comment]
@lukyanoffpashok could you please review also, since it's your issue?

**Comment by lukyanoffpashok** [comment]
In the metric need to increase counter for every call. For example, if the method value() was called 3 times, the counter should be increased by 3, not by 1.

**Comment by paulodamaso** [comment]
@lukyanoffpashok Done, please take a look. Also changed the pattern name to reflect better what is being counted

**Comment by paulodamaso** [comment]
@lukyanoffpashok ping

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4ea0ebc5-1e90-4d29-b5a1-8c93eef19bcd, thread: PQ-CT5UB7XAP
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-boosts.xsl says: The boost for job "gh:yegor256/aibolit#244" exists in boosts.xml, but the job is absent in the WBS among 22 jobs.
```

[0.53.13](https://github.com/zerocracy/farm): CID: [f506f201-a700-44d4-91ef-8f8e6df782d0](https://www.0crat.com/footprint/CT5UB7XAP/f506f201-a700-44d4-91ef-8f8e6df782d0), Type: "Remove job from WBS"

**Pull request merged**
