### PR TITLE
Log errors red catch

### PR DESCRIPTION
**Pull request by lyriccoder**
https://github.com/yegor256/aibolit/issues/175

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#176](https://github.com/yegor256/aibolit/issues/176) is assigned to @tribals[/z](https://www.0crat.com/u/tribals), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/6cdcaf46-9d01-45db-9454-3bac3b70be5b); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by acheshkov** [comment]
@0crat reject

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat reject ([here](https://github.com/yegor256/aibolit/issues/176#issuecomment-611038757))

@acheshkov The user @tribals[/z](https://www.0crat.com/u/tribals) resigned from [#176](https://github.com/yegor256/aibolit/issues/176), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
This pull request [#176](https://github.com/yegor256/aibolit/issues/176) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/37a682f5-0792-4742-82a1-efb09a58d72b); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 16 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)[/z](https://www.0crat.com/u/fanifieiev) didn't make CR comments

**Pull request merged**
