### PR TITLE
Issue 228. Integration test.

### PR DESCRIPTION
**Pull request by acheshkov**
* Integration test is added
* Some patterns/metrics excluded from test till not fixed
* Some fixes for patterns

### CODE REVIEW

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/232#issuecomment-617094181))

@acheshkov Job `gh:yegor256/aibolit#232` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/232#issuecomment-617094181))

@acheshkov Pull request [#232](https://github.com/yegor256/aibolit/issues/232) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#232` is not assigned, can't get performer

**Pull request merged**
