### PR TITLE
fixing #229: Fix 04-patterns.py due to engine refactor

### PR DESCRIPTION
**Pull request by lyriccoder**
fixing https://github.com/yegor256/aibolit/issues/229

### CODE REVIEW

**Comment by lyriccoder** [comment]
do not review, i will talk about it with @acheshkov

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/230#issuecomment-616594309))

@acheshkov Job `gh:yegor256/aibolit#230` is not assigned, can't get performer

**Comment by 0crat** [comment]
This pull request [#230](https://github.com/yegor256/aibolit/issues/230) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/a692d821-2929-4e8f-b6ac-25d1ff65a3f2); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by fanifieiev** [comment]
@0crat refuse

**Comment by 0crat** [comment]
This pull request [#230](https://github.com/yegor256/aibolit/issues/230) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/2705c1b1-2d61-4107-83e6-6ab06ae386b9); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/aibolit/issues/230#issuecomment-616629282))

@fanifieiev Job refused in 0 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/aibolit/issues/230#issuecomment-616865999))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#230](https://github.com/yegor256/aibolit/issues/230), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/aibolit/issues/230#issuecomment-616865999))

@carlosmiranda Job refused in 16 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/230#issuecomment-617090943))

@acheshkov GitHub issue is still open, won't close

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/230#issuecomment-617090943))

@acheshkov Job [#230](https://github.com/yegor256/aibolit/issues/230) is not in the agenda of @tribals[/z](https://www.0crat.com/u/tribals), can't set title

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#230](https://github.com/yegor256/aibolit/issues/230) is not in the agenda of @tribals[/z](https://www.0crat.com/u/tribals), can't set title

**Comment by 0crat** [comment]
Job was finished in 8 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @tribals[/z](https://www.0crat.com/u/tribals)[/z](https://www.0crat.com/u/tribals) didn't make CR comments

**Pull request merged**
