### PR TITLE
one more test for multi-line function call

### PR DESCRIPTION
**Pull request by acheshkov**
I've added one more test case to test pattern "Line diff between usage and declaration of a variable".

### CODE REVIEW

**Comment by paulodamaso** [comment]
@g4s8 please assign me

**Comment by paulodamaso** [comment]
@yegor256 please assign me, I'm available

**Comment by yegor256** [comment]
@acheshkov ready to go

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#57` is not assigned, can't get performer

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Pull request merged**
