### PR TITLE
Fix part sync with ctrs and lambdas

### PR DESCRIPTION
**Pull request by lyriccoder**
https://github.com/yegor256/aibolit/issues/260

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#261](https://github.com/yegor256/aibolit/issues/261) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/63d9a0b3-93b6-4259-b23c-b56108d8e082); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by lyriccoder** [comment]
@0crat assign to @acheshkov

**Comment by 0crat** [comment]
> @0crat assign to @acheshkov  ([here](https://github.com/yegor256/aibolit/issues/261#issuecomment-624624186))

@lyriccoder You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by lyriccoder** [comment]
@acheshkov Fixed

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 23 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)[/z](https://www.0crat.com/u/carlosmiranda) didn't make CR comments

**Pull request merged**
