### PR TITLE
Implement Aibolit with Python script and Maven installation

### PR DESCRIPTION
**Pull request by zuoqin**

### CODE REVIEW

**Comment by yegor256** [comment]
@zuoqin looks good for a start. However, it should be a class, not a script. We need a class, which accepts a path to a file and returns CC. Also, we need a unit test for this class. Also, please put everything into `aibolit/metrics/cc`

**Comment by zuoqin** [comment]
@yegor256, CCmetric class implemented, build script created, directory changed, unit tests are run

**Comment by yegor256** [comment]
@zuoqin please see what Travis CI says, there are issues

**Comment by yegor256** [comment]
@zuoqin thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#3` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
