### PR TITLE
Update classic_setter pattern with new assert and minor conditions

### PR DESCRIPTION
**Pull request by silverCase**
Resolving #121

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#151](https://github.com/yegor256/aibolit/issues/151) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/a1e696b5-9e9a-4c8d-84a6-55ace613484e); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by fanifieiev** [comment]
@silverCase Could you please resolve branch conflicts first ?

**Comment by silverCase** [comment]
Done!

**Comment by 0crat** [comment]
Job audit: `ARC` didn't merge or close PR

**Comment by 0crat** [comment]
Pull request [#151](https://github.com/yegor256/aibolit/issues/151) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
