### PR TITLE
Pattern: class have to be final

### LINKED ISSUE #143: non_final_class pattern
Once we see a class that doesn't have `final` modifier, it's a pattern. It's a good practice to make all classes final: https://www.yegor256.com/2014/11/20/seven-virtues-of-good-object.html

### PR DESCRIPTION
**Pull request by acheshkov**
closes #143

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#188](https://github.com/yegor256/aibolit/issues/188) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/d00c047b-7977-4b9c-b6e9-2f57ed746ae0); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by fanifieiev** [comment]
@acheshkov What about abstract class ? Abstract class has no final modifier.

**Comment by acheshkov** [comment]
> @acheshkov What about abstract class ? Abstract class has no final modifier.

@fanifieiev Not a word about abstract class in the issue. @yegor256 could you comment on that?

**Comment by yegor256** [comment]
@acheshkov abstract classes must be ignored by this pattern

**Comment by acheshkov** [comment]
@fanifieiev please continue review

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 23 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Pull request merged**
