### PR TITLE
AST refactoring.

### PR DESCRIPTION
**Pull request by aravij**
Functionality of AST was splited into two separate modules: encoding_detector and ast_builder.
This refactoring also decrease number of times we read file, while building ast (from 2 to 1).

This commits was part of issue-340 branch, but were separated into different issue.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#391](https://github.com/yegor256/aibolit/issues/391) is assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/06205dd6-d3a2-46d0-80d8-41e721dbbda8); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by lyriccoder** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/aibolit/issues/391#issuecomment-639532715))

@lyriccoder The user @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) resigned from [#391](https://github.com/yegor256/aibolit/issues/391), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/aibolit/issues/391#issuecomment-639532715))

@lyriccoder Job refused in 19 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by aravij** [comment]
@lyriccoder are you going to explain, why you have refused my PR. Or I have to guess it on my own?

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#391` is not assigned, can't get performer

**Pull request merged**
