### PR TITLE
For #281: method_siblings pattern implementation

### PR DESCRIPTION
**Pull request by paulodamaso**
For #281:
- implemented `method_siblings` pattern
- changed the test: I think that it's more logical to return all occurrences of methods which have siblings instead just the first one

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#347](https://github.com/yegor256/aibolit/issues/347) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/3eb866b9-0922-4e36-81c7-4e735f891871); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by lyriccoder** [comment]
@paulodamaso  is it possible to make an interface or join `method_sibling` and  `var_siblings`? They have the same regexp and similar logic (variable names vs function names). Is it possible to create an separate class for it? I think must reuse this implementation. Otherwise, we will have to fix code in 2 place, while we have similar implementation

**Comment by paulodamaso** [comment]
@lyriccoder I'm afraid that it won't be possible: the code is different for both implementations and we have different properties for the element name when we use `javalang.tree.MethodDeclaration` and `javalang.tree.LocalVariableDeclaration`

**Comment by paulodamaso** [comment]
@carlosmiranda ping

**Comment by paulodamaso** [comment]
@acheshkov ping

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job audit: performer @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)[/z](https://www.0crat.com/u/carlosmiranda) didn't make CR comments

**Comment by 0crat** [comment]
Code review was too long (31 days), architects (@acheshkov) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Pull request merged**
