### PR TITLE
added considering nested methods and added typings

### PR DESCRIPTION
**Pull request by Vitaly-Protasov**
Fixed https://github.com/yegor256/aibolit/issues/221

### CODE REVIEW

**Comment by acheshkov** [comment]
@0crat out

**Comment by acheshkov** [comment]
thanks!

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat out  ([here](https://github.com/yegor256/aibolit/issues/222#issuecomment-615291016))

@acheshkov Job `gh:yegor256/aibolit#222` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#222` doesn't exist in WBS, can't create order

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#222` is not assigned, can't get performer

**Pull request merged**
