### PR TITLE
Replace bare `assert` statements with `unittest.TestCase` assertion methods

### LINKED ISSUE #107: Use assert methods of `unittest.TestCase` class rather than bare `assert` statement in tests
If you're using stdlib's `unittest` package for writing tests, you shouldn't use "bare" `assert` statements. They are intended for different purposes - to provide [quick-fail validation](https://wiki.python.org/moin/UsingAssertionsEffectively) of function call preconditions. But even this usage is considered an anti-pattern in community.

The issue is that `assert` statement could be [stripped out by interpreter when you turn optimization on](https://docs.python.org/3/using/cmdline.html#cmdoption-o), so your _tests will never fail_. I'll cite docs here for conveniece:

> -O
Remove assert statements and any code conditional on the value of `__debug__`. Augment the filename for compiled (bytecode) files by adding `.opt-1` before the `.pyc` extension (see PEP 488). See also PYTHONOPTIMIZE.

Here is example.

We have simple test:

```python
from unittest import TestCase


class TestTruth(TestCase):
    def test_true_is_false_bare_assert(self):
        assert True is False

    def test_true_is_false_assert_method(self):
        self.assertEqual(True, False)
```

Let's run it!

```console
$ python3 -m unittest test_truth.py 
FF
======================================================================
FAIL: test_true_is_false_assert_method (test_truth.TestTruth)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tosh/spikes/python-bare-assert/test_truth.py", line 9, in test_true_is_false_assert_method
    self.assertEqual(True, False)
AssertionError: True != False

======================================================================
FAIL: test_true_is_false_bare_assert (test_truth.TestTruth)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tosh/spikes/python-bare-assert/test_truth.py", line 6, in test_true_is_false_bare_assert
    assert True is False
AssertionError

----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (failures=2)
```

As you would expect, they both fails.

But let's turn optimization now (note added `-O` switch)!

```console
$ python3 -O -m unittest test_truth.py 
F.
======================================================================
FAIL: test_true_is_false_assert_method (test_truth.TestTruth)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tosh/spikes/python-bare-assert/test_truth.py", line 9, in test_true_is_false_assert_method
    self.assertEqual(True, False)
AssertionError: True != False

----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (failures=1)
```

As you'll see, now only one test fails - the one that uses assert method rather than `assert` statement.

So, if you decided to write tests using stdlib's `unittest` package, you must use assert methods. Another option will be to switch testing framework. For example, there is [`pytest`](https://docs.pytest.org/en/latest/) framework, which "overloads" `assert` statement.

Let's run our test with `pytest` (with optimization turned on):

```console
$ pip3 install pytest
$ python3 -O -m pytest -q test_truth.py
WARNING: assertions not in test modules or plugins will be ignored because assert statements are not executed by the underlying Python interpreter (are you using python -O?)
FF                                                                                         [100%]
============================================ FAILURES ============================================
___________________________ TestTruth.test_true_is_false_assert_method ___________________________

self = <test_truth.TestTruth testMethod=test_true_is_false_assert_method>

    def test_true_is_false_assert_method(self):
>       self.assertEqual(True, False)
E       AssertionError: True != False

test_truth.py:9: AssertionError
____________________________ TestTruth.test_true_is_false_bare_assert ____________________________

self = <test_truth.TestTruth testMethod=test_true_is_false_bare_assert>

    def test_true_is_false_bare_assert(self):
>       assert True is False
E       assert True is False

test_truth.py:6: AssertionError
==================================== short test summary info =====================================
FAILED test_truth.py::TestTruth::test_true_is_false_assert_method - AssertionError: True != False
FAILED test_truth.py::TestTruth::test_true_is_false_bare_assert - assert True is False
2 failed in 0.03s
```

Note that `pytest` even warns you about bare `assert` statements. It is also more relaxed in other handy ways by contrast to `unittest` and can run `unittest`-style tests without additional configuration.

### PR DESCRIPTION
**Pull request by tribals**
Closes #107

### CODE REVIEW

**Comment by tribals** [comment]
@acheshkov Please, review

**Comment by tribals** [comment]
@acheshkov I resolved conflicts, now able to merge.

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
This pull request [#115](https://github.com/yegor256/aibolit/issues/115) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/0db2da18-5e96-4db6-a41e-7256d4482ece); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)[/z](https://www.0crat.com/u/fanifieiev) didn't make CR comments

**Pull request merged**
