### PR TITLE
Fix 383

### PR DESCRIPTION
**Pull request by lyriccoder**
fix https://github.com/yegor256/aibolit/issues/383

### CODE REVIEW

**Comment by lyriccoder** [comment]
Report will look like:

```
<report>
	<header>
		<score>30.016422284757933</score>
		<!--datetime in ms-->
		<datetime>1591278729484</datetime>
		<version>0.0.0</version>
		<cmd>/mnt/d/git/aibolit/aibolit/__main__.py recommend --folder=/mnt/d/target/0001/fast --format=compact --full</cmd>
		<exit_code>0</exit_code>
	</header>
	<!--Show all patterns-->
	<files>
		<file>
			<path>D:\\target\\0001\\fast\\Configuration.java</path>
			<summary>Some issues found</summary>
			<score>48.85284456951587</score>
			<patterns>
				<pattern code="P13">
					<details>Null check</details>
					<score>30.95612931128819</score>
					<order>1/2</order>
					<lines>
						<number>294</number>
						<number>391</number>
					</lines>
				</pattern>
				<pattern code="P12">
					<details>Non final attribute</details>
					<score>17.89671525822768</score>
					<order>2/2</order>
					<lines>
						<number>235</number>
						<number>240</number>
					</lines>
				</pattern>
			</patterns>
		</file>
		<file>
			<path>D:\\target\\0001\\fast\\Error.java</path>
			<summary>Error when calculating patterns: Smth happened</summary>
		</file>
		<file>
			<path>D:\\target\\0001\\fast\\Another.java</path>
			<summary>Some issues found</summary>
			<score>11.18</score>
			<patterns>
				<pattern code="P13">
					<details>Null check</details>
					<score>10.95</score>
					<order>1/2</order>
					<lines>
						<number>23</number>
						<number>2</number>
					</lines>
				</pattern>
				<pattern code="P12">
					<details>Non final attribute</details>
					<score>0.23</score>
					<order>2/2</order>
					<lines>
						<number>235</number>
						<number>240</number>
					</lines>
				</pattern>
			</patterns>
		</file>
	</files>
</report>
```

**Comment by 0crat** [comment]
This pull request [#389](https://github.com/yegor256/aibolit/issues/389) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/3181732d-5742-4708-b03c-8ced2f28a0d1); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by acheshkov** [comment]
@0crat out

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat out  ([here](https://github.com/yegor256/aibolit/issues/389#issuecomment-639470693))

@acheshkov GitHub issue is still open, won't close

**Comment by 0crat** [comment]
Job audit: performer @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)[/z](https://www.0crat.com/u/paulodamaso) didn't make CR comments

**Comment by 0crat** [comment]
Job was finished in 19 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ca467921-5714-4665-aa83-dab65ec69cb4, thread: PQ-CT5UB7XAP
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.cost.pay_cash
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: java.io.IOException: Failed to add transaction
com.zerocracy.pm.cost.Ledger[133] java.io.IOException: Failed to add transaction
org.postgresql.jdbc.PgConnection[767] org.postgresql.util.PSQLException: This connection has been closed.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [876013cd-571c-4a15-88f6-909571dd853d](https://www.0crat.com/footprint/CT5UB7XAP/876013cd-571c-4a15-88f6-909571dd853d), Type: "Pay cash"

**Pull request merged**
