### PR TITLE
fixed var in the middle  for multi-line statements and empty lines

### PR DESCRIPTION
**Pull request by acheshkov**
The issue with var in the middle is fixed, tests are added

### CODE REVIEW

**Comment by acheshkov** [comment]
@yegor256, @lyriccoder please review

**Comment by paulodamaso** [comment]
@g4s8 Please assign me, I'm available

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#53` is not assigned, can't get performer

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Pull request merged**
