### PR TITLE
Used_fields property for java methods.

### PR DESCRIPTION
**Pull request by aravij**
Also added `parameters` property to view parameters of method.
AST constructor changed to be more simple. Constructing AST from javalang node is now done by static method.

### CODE REVIEW

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@592e6706-44da-4634-a6e2-8ab630bff16f, thread: PQ-CT5UB7XAP
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Evaluate pattern on arbitary AST' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [364da245-d373-4c5b-8ce5-fc42035085ad](https://www.0crat.com/footprint/CT5UB7XAP/364da245-d373-4c5b-8ce5-fc42035085ad), Type: "Job milestoned"

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @aravij[/z](https://www.0crat.com/u/aravij) are: `DEV`, `REV`

**Comment by 0crat** [comment]
This pull request [#442](https://github.com/yegor256/aibolit/issues/442) is assigned to @aravij[/z](https://www.0crat.com/u/aravij), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/8a65acb3-3a20-4576-8efe-3c131ff366c1); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@aravij take a look

**Comment by aravij** [comment]
@acheshkov It should work now

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
@aravij[/z](https://www.0crat.com/u/aravij) resigned from [#442](https://github.com/yegor256/aibolit/issues/442), since the job is not in scope anymore

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c7fc22bc-bc34-4b92-886c-5bb37239a1aa, thread: PQ-CT5UB7XAP
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:yegor256/aibolit#442] declared for identity constraint of element "speed".
```

[0.53.15](https://github.com/zerocracy/farm): CID: [9b9647e2-da56-49a3-b0d8-62ccb40ecd1a](https://www.0crat.com/footprint/CT5UB7XAP/9b9647e2-da56-49a3-b0d8-62ccb40ecd1a), Type: "Order was canceled"

**Pull request merged**
