### PR TITLE
Two_Fold ranking model. Jupyter

### PR DESCRIPTION
**Pull request by angusev**
Add Two_Fold ranking model

### CODE REVIEW

**Comment by angusev** [comment]
@acheshkov

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#205` is not assigned, can't get performer

**Comment by 0crat** [comment]
Pull request [#205](https://github.com/yegor256/aibolit/issues/205) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/205#issuecomment-613004735))

@acheshkov Job `gh:yegor256/aibolit#205` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#205` is not assigned, can't get performer

**Pull request closed without merging**
