### PR TITLE
Task #7 Create script to download Java repositories

### PR DESCRIPTION
**Pull request by zuoqin**

### CODE REVIEW

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this pull request

**Comment by yegor256** [comment]
@zuoqin please check what Travis CI is saying

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#8` is not assigned, can't get performer

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `REV` is banned at [#8](https://github.com/yegor256/aibolit/issues/8); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Pull request merged**
