### PR TITLE
Pattern: Nested Loop 

### PR DESCRIPTION
**Pull request by acheshkov**
Closes: #137

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#189](https://github.com/yegor256/aibolit/issues/189) is assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/66707a9f-de8f-4c86-8f04-8ecad64d4190); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by lyriccoder** [comment]
I would add more test for loops with anonymous classes and lambda functions. But it's ok if you want to do it later. Approve

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Pull request merged**
