### PR TITLE
Add score to xml

### PR DESCRIPTION
**Pull request by lyriccoder**
fix https://github.com/yegor256/aibolit/issues/327

### CODE REVIEW

**Comment by lyriccoder** [comment]
@acheshkov need to discuss. Do we need to break calculations, score will not differ in this case

**Comment by 0crat** [comment]
This pull request [#328](https://github.com/yegor256/aibolit/issues/328) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/90734639-2e35-4499-8f24-8f4ddc3cae4c); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@lyriccoder I'll refuse it for now, @acheshkov you can assing it to me once it is done

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/aibolit/issues/328#issuecomment-631041289))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#328](https://github.com/yegor256/aibolit/issues/328), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/aibolit/issues/328#issuecomment-631041289))

@paulodamaso Job refused in 1 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
Job [#328](https://github.com/yegor256/aibolit/issues/328) is already in scope

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/328#issuecomment-631375277))

@acheshkov Job `gh:yegor256/aibolit#328` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/328#issuecomment-631375277))

@acheshkov Pull request [#328](https://github.com/yegor256/aibolit/issues/328) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#328` is not assigned, can't get performer

**Pull request merged**
