### PR TITLE
Now aibolit can check the latest version available

### LINKED ISSUE #388: Check for updates when aibolit is loaded
just a warning if there is a newer version of aibolit

### PR DESCRIPTION
**Pull request by lyriccoder**
fix #388

### CODE REVIEW

**Comment by lyriccoder** [comment]
Retry DeepCode

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
This pull request [#394](https://github.com/yegor256/aibolit/issues/394) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/899abc16-290b-44ac-bdae-8b4b5e1529ff); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 17 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)[/z](https://www.0crat.com/u/paulodamaso) didn't make CR comments

**Pull request merged**
