### PR TITLE
For #144: added mutable_class pattern tests

### PR DESCRIPTION
**Pull request by paulodamaso**
For #144: 
- added `mutable_class` pattern tests for various cases
- left puzzle for finishing implementing `mutable_class` pattern

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#277](https://github.com/yegor256/aibolit/issues/277) is assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/8e0988fa-37f5-4639-80ab-f4ead31c02b0); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by lyriccoder** [comment]
Duplicate of 118

**Comment by lyriccoder** [comment]
@acheshkov should we close it?

**Comment by 0crat** [comment]
Job audit: `ARC` didn't merge or close PR

**Comment by 0crat** [comment]
Pull request [#277](https://github.com/yegor256/aibolit/issues/277) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
