### PR TITLE
White Paper LaTeX

### PR DESCRIPTION
**Pull request by acheshkov**
Whiter paper TeX document

### CODE REVIEW

**Comment by acheshkov** [comment]
@0crat reject

**Comment by 0crat** [comment]
> @0crat reject  ([here](https://github.com/yegor256/aibolit/issues/171#issuecomment-610798788))

@acheshkov Job `gh:yegor256/aibolit#171` is not assigned, can't get performer

**Comment by 0crat** [comment]
This pull request [#171](https://github.com/yegor256/aibolit/issues/171) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/c5baf37e-71b7-49cb-aea2-008f29ae5d7c); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)[/z](https://www.0crat.com/u/fanifieiev) didn't make CR comments

**Pull request merged**
