### PR TITLE
Fix method in ast

### PR DESCRIPTION
**Pull request by lukyanoffpashok**

### CODE REVIEW

**Comment by 0crat** [comment]
@lukyanoffpashok[/z](https://www.0crat.com/u/lukyanoffpashok) this pull request is too small, just 9 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @acheshkov[/z](https://www.0crat.com/u/acheshkov) please review this and merge or reject

**Comment by aravij** [comment]
@acheshkov  please merge

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@lukyanoffpashok there are merge conflicts

**Comment by lukyanoffpashok** [comment]
@acheshkov please merge

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#457` is not assigned, can't get performer

**Pull request merged**
