### PR TITLE
var in the middle pattern now works with nested classes and methods

### PR DESCRIPTION
**Pull request by acheshkov**
Var in the middle patterns now works with nested classes and methods.

### CODE REVIEW

**Comment by paulodamaso** [comment]
@yegor256 I can review it, please assign me

**Comment by yegor256** [comment]
@acheshkov good to go

**Comment by acheshkov** [comment]
@rultor merge please

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#63` is not assigned, can't get performer

**Pull request merged**
