### PR TITLE
Fix for out.xml structure is weird #339

### LINKED ISSUE #339: out.xml structure is weird
This is what I see:

```xml
<filename>/code/cactoos/src/test/java/org/cactoos/iterable/SyncedTest.java<patterns><pattern pattern_code="P10">Method chain<code_lines><line_number>45</line_number><line_number>46</line_number></code_lines></pattern></patterns><maintainability_score>1.8902023340148628</maintainability_score></filename>
```

The idea of combining text contents and elements is very bad. Instead, make it like this:

```xml
<file>
  <filename></filename>
  <patterns>...</patterns>
</file>
```

### PR DESCRIPTION
**Pull request by lyriccoder**
Fix #339 https://github.com/yegor256/aibolit/issues/342

### CODE REVIEW

**Comment by lyriccoder** [comment]
merge when https://github.com/yegor256/aibolit/pull/335 is ready

**Comment by 0crat** [comment]
This pull request [#345](https://github.com/yegor256/aibolit/issues/345) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/940e41b6-776c-49e2-8084-6e2e40899e0b); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@lyriccoder I think that we should have a test that assures the correct generation of XML. We could generate a sample xml executing the patterns over some files and then check the generated xml structure and values, WDYT?

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 3 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Pull request merged**
