### PR TITLE
image name changed

### PR DESCRIPTION
**Pull request by acheshkov**

### CODE REVIEW

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @acheshkov[/z](https://www.0crat.com/u/acheshkov) please review this and merge or reject

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/268#issuecomment-624778087))

@acheshkov Job `gh:yegor256/aibolit#268` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#268` is not assigned, can't get performer

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#268` is not assigned, can't get performer

**Pull request merged**
