### PR TITLE
fixed errors in unittest and upgraded code

### PR DESCRIPTION
**Pull request by Vitaly-Protasov**

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#185](https://github.com/yegor256/aibolit/issues/185) is assigned to @tribals[/z](https://www.0crat.com/u/tribals), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/0ce5df7f-e265-43f2-818f-2ecc86d34d24); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by tribals** [comment]
@Vitaly-Protasov For which task this PR is?

**Comment by Vitaly-Protasov** [comment]
@tribals That's for pattern "If return if", which I implemented earlier. Fixed one extra class and form more understandable version of it. Also, unittest recognizes errors, I fixed them in code.

**Comment by tribals** [comment]
@Vitaly-Protasov I mean, for which exact issue number it is?

**Comment by Vitaly-Protasov** [comment]
@tribals not not for any particular issue. It just i noticed and decided to fix:)

**Comment by lyriccoder** [comment]
@Vitaly-Protasov  you should create an issue first, and then make a link to it in a pull request

**Comment by tribals** [comment]
@acheshkov Please, decline this PR.

**Comment by tribals** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/aibolit/issues/185#issuecomment-611717264))

@tribals The user @tribals[/z](https://www.0crat.com/u/tribals) resigned from [#185](https://github.com/yegor256/aibolit/issues/185), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
This pull request [#185](https://github.com/yegor256/aibolit/issues/185) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/1c2db78e-2c0c-4876-a282-d20e33c95343); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 11 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: `ARC` didn't merge or close PR, performer @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)[/z](https://www.0crat.com/u/fanifieiev) didn't make CR comments

**Comment by 0crat** [comment]
Pull request [#185](https://github.com/yegor256/aibolit/issues/185) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
