### PR TITLE
Ignore java files for Deepcode

### LINKED ISSUE #397: add ignore file for deepcode

### PR DESCRIPTION
**Pull request by lyriccoder**
fix #397 
We do not need to analyze Java files in our projects since they are tests. They can be written in a bad way intentionally

### CODE REVIEW

**Comment by lyriccoder** [comment]
@acheshkov pls merge

**Comment by acheshkov** [comment]
@rultor merge

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@964e303f-91b1-49ab-afed-1b886adbfcd3, thread: pool-237-thread-1
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/aibolit' repo was not found
```

[0.54.5](https://github.com/zerocracy/farm): Issue: cqfn/aibolit#398, Comment: 667843995

**Pull request merged**
