### PR TITLE
Skip collect dataset

### PR DESCRIPTION
**Pull request by lyriccoder**
Add parameter to skip dataset collection
https://github.com/yegor256/aibolit/issues/315

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#313](https://github.com/yegor256/aibolit/issues/313) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/fbf27d68-a124-4b74-8fbc-6536ab858ccf); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/313#issuecomment-629286195))

@acheshkov GitHub issue is still open, won't close

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)[/z](https://www.0crat.com/u/carlosmiranda) didn't make CR comments

**Comment by 0pdd** [comment]
@lyriccoder the only puzzle [#754](https://github.com/cqfn/aibolit/issues/754) is solved here.

**Pull request merged**
