### PR TITLE
New release 0.0.6. 

### PR DESCRIPTION
**Pull request by lyriccoder**
1. script for calculating all patterns was modified to gather error log
2. new model was added
3. different fixes with types.py, etc.

https://github.com/yegor256/aibolit/issues/199

### CODE REVIEW

**Comment by acheshkov** [comment]
@0crat out

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/200#issuecomment-612055601))

@acheshkov Job `gh:yegor256/aibolit#200` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/200#issuecomment-612055601))

@acheshkov Pull request [#200](https://github.com/yegor256/aibolit/issues/200) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@rultor release tag is `0.0.6`

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#200` is not assigned, can't get performer

**Pull request merged**
