### PR TITLE
For #138: added while loop tests for loop outsider pattern

### PR DESCRIPTION
**Pull request by paulodamaso**
For #138: 
- added while loop tests for loop outsider pattern
- left puzzle for implementing for and do-while loops; making all the tests in just one PR would make it too big

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#250](https://github.com/yegor256/aibolit/issues/250) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/01c51048-6c15-4ecf-91ab-5448f8570eb6); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by acheshkov** [comment]
@carlosmiranda you are assigned as a reviewer here.

**Comment by paulodamaso** [comment]
@acheshkov He approved without comments I think. Please merge

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
Job audit: performer @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)[/z](https://www.0crat.com/u/carlosmiranda) didn't make CR comments

**Pull request merged**
