### PR TITLE
Added new metric of max diameter in AST (Fixed #167 Issue)

### LINKED ISSUE #167: Metric: Maximum length of the path between identifiers in AST
Here I'll try to overview an idea of the mentioned metric at the topic.

Our purpose is to get the maximum size of the path between leaves in AST. 
It can be conducted by traversing through the AST of code snippet.

Let's consider an example at  the code snippet and its AST representation:
image

### As the examples you can considere color paths:
* lenght of the **green** one is 5
* lenght of the **yellow** one is 5
* of the **blue** one is 8
* of the **red** one is 10
* etc for others

### Max lenght of paths between leaves at this code snippet is **12**
*  Object -> Class -> Parameter -> MethodDecl -> Block -> Foreach -> Block -> IfStmt -> Block -> Return -> BooleanExpr -> true
* target -> VarDeclId-> Parameter -> MethodDecl -> Block -> Foreach -> Block -> IfStmt -> Block -> Return -> BooleanExpr -> true

**The same should work and for Class object.**

### PR DESCRIPTION
**Pull request by Vitaly-Protasov**
Fixing #167

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#186](https://github.com/yegor256/aibolit/issues/186) is assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/88e148e6-1b24-4f33-8f79-c2147f4aa215); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by acheshkov** [comment]
@rultor merge

**Comment by acheshkov** [comment]
@Vitaly-Protasov see above, flake8 issues

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 41 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @lyriccoder[/z](https://www.0crat.com/u/lyriccoder)[/z](https://www.0crat.com/u/lyriccoder) didn't make CR comments

**Pull request merged**
