### PR TITLE
Cognitive complexity. Added detecting recursion call

### PR DESCRIPTION
**Pull request by Vitaly-Protasov**
Solved https://github.com/yegor256/aibolit/issues/219

Also added incrementing level for nested methods

### CODE REVIEW

**Comment by acheshkov** [comment]
@0crat out

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/220#issuecomment-615204202))

@acheshkov GitHub issue is still open, won't close

**Comment by 0crat** [comment]
This pull request [#220](https://github.com/yegor256/aibolit/issues/220) is assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/442a2337-9aee-4219-8680-92ef3073243d); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @acheshkov[/z](https://www.0crat.com/u/acheshkov) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/220#issuecomment-615204202))

@acheshkov Job [#220](https://github.com/yegor256/aibolit/issues/220) is not in the agenda of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), can't set title

**Comment by acheshkov** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @lyriccoder[/z](https://www.0crat.com/u/lyriccoder)[/z](https://www.0crat.com/u/lyriccoder) didn't make CR comments

**Pull request merged**
